// Best-effort food-emoji lookup for pantry items. Keeps the chips readable
// at a glance without pulling a custom icon set. Falls back to a generic
// plate emoji for anything we don't recognize.

const MAP: Record<string, string> = {
  chicken: '🍗',
  rice: '🍚',
  eggs: '🥚',
  egg: '🥚',
  pasta: '🍝',
  noodles: '🍜',
  broccoli: '🥦',
  beef: '🥩',
  steak: '🥩',
  pork: '🥓',
  bacon: '🥓',
  onion: '🧅',
  garlic: '🧄',
  tomato: '🍅',
  cheese: '🧀',
  oats: '🌾',
  oat: '🌾',
  salmon: '🐟',
  fish: '🐟',
  tuna: '🐟',
  shrimp: '🍤',
  spinach: '🥬',
  lettuce: '🥬',
  kale: '🥬',
  butter: '🧈',
  lentils: '🫘',
  beans: '🫘',
  chickpeas: '🫘',
  tortilla: '🫓',
  bread: '🍞',
  yogurt: '🥛',
  milk: '🥛',
  oil: '🫒',
  'olive oil': '🫒',
  salt: '🧂',
  pepper: '🌶️',
  carrot: '🥕',
  potato: '🥔',
  sweetpotato: '🍠',
  'sweet potato': '🍠',
  avocado: '🥑',
  banana: '🍌',
  apple: '🍎',
  berries: '🫐',
  blueberries: '🫐',
  strawberries: '🍓',
  lemon: '🍋',
  lime: '🍋',
  corn: '🌽',
  mushroom: '🍄',
  mushrooms: '🍄',
  cucumber: '🥒',
  pepperbell: '🫑',
  'bell pepper': '🫑',
  honey: '🍯',
  peanut: '🥜',
  peanuts: '🥜',
  almond: '🥜',
  almonds: '🥜',
  nuts: '🥜',
  tofu: '🥡',
  tempeh: '🥡',
  cabbage: '🥬',
  pineapple: '🍍',
};

export function foodEmoji(name: string): string {
  const key = name.trim().toLowerCase();
  return MAP[key] ?? '🥗';
}
